In [1]:
!cp -r /kaggle/input/datasets/baohg153/prover9/Prover9-LADR-2026-4F /kaggle/working/

%cd /kaggle/working/Prover9-LADR-2026-4F
!make all STATIC=1
%cd /kaggle/working/

/kaggle/working/Prover9-LADR-2026-4F
cd ladr         && make lib
make[1]: Entering directory '/kaggle/working/Prover9-LADR-2026-4F/ladr'
make libladr.a
make[2]: Entering directory '/kaggle/working/Prover9-LADR-2026-4F/ladr'
ladr: build mode changed to release, rebuilding...
gcc -O2 -Wall -MMD -MP     -c -o order.o order.c
gcc -O2 -Wall -MMD -MP     -c -o clock.o clock.c
gcc -O2 -Wall -MMD -MP     -c -o nonport.o nonport.c
gcc -O2 -Wall -MMD -MP     -c -o fatal.o fatal.c
gcc -O2 -Wall -MMD -MP     -c -o ibuffer.o ibuffer.c
gcc -O2 -Wall -MMD -MP     -c -o memory.o memory.c
gcc -O2 -Wall -MMD -MP     -c -o hash.o hash.c
gcc -O2 -Wall -MMD -MP     -c -o string.o string.c
gcc -O2 -Wall -MMD -MP     -c -o strbuf.o strbuf.c
gcc -O2 -Wall -MMD -MP     -c -o glist.o glist.c
gcc -O2 -Wall -MMD -MP     -c -o options.o options.c
gcc -O2 -Wall -MMD -MP     -c -o symbols.o symbols.c
gcc -O2 -Wall -MMD -MP     -c -o avltree.o avltree.c
gcc -O2 -Wall -MMD -MP     -c -o term.o term.c
gcc -O2 -Wall -MMD -MP     -c -o termflag.o termflag.c
gcc -O2 -Wall -MMD -MP     -c -o listterm.o listterm.c
gcc -O2 -Wall -MMD -MP     -c -o tlist.o tlist.c
gcc -O2 -Wall -MMD -MP     -c -o flatterm.o flatterm.c
gcc -O2 -Wall -MMD -MP     -c -o multiset.o multiset.c
gcc -O2 -Wall -MMD -MP     -c -o termorder.o termorder.c
gcc -O2 -Wall -MMD -MP     -c -o parse.o parse.c
gcc -O2 -Wall -MMD -MP     -c -o accanon.o accanon.c
gcc -O2 -Wall -MMD -MP     -c -o unify.o unify.c
gcc -O2 -Wall -MMD -MP     -c -o fpalist.o fpalist.c
gcc -O2 -Wall -MMD -MP     -c -o fpa.o fpa.c
gcc -O2 -Wall -MMD -MP     -c -o discrim.o discrim.c
gcc -O2 -Wall -MMD -MP     -c -o discrimb.o discrimb.c
gcc -O2 -Wall -MMD -MP     -c -o discrimw.o discrimw.c
gcc -O2 -Wall -MMD -MP     -c -o dioph.o dioph.c
gcc -O2 -Wall -MMD -MP     -c -o btu.o btu.c
gcc -O2 -Wall -MMD -MP     -c -o btm.o btm.c
gcc -O2 -Wall -MMD -MP     -c -o mindex.o mindex.c
gcc -O2 -Wall -MMD -MP     -c -o basic.o basic.c
gcc -O2 -Wall -MMD -MP     -c -o attrib.o attrib.c
gcc -O2 -Wall -MMD -MP     -c -o formula.o formula.c
gcc -O2 -Wall -MMD -MP     -c -o definitions.o definitions.c
gcc -O2 -Wall -MMD -MP     -c -o literals.o literals.c
gcc -O2 -Wall -MMD -MP     -c -o topform.o topform.c
gcc -O2 -Wall -MMD -MP     -c -o clist.o clist.c
gcc -O2 -Wall -MMD -MP     -c -o clauseid.o clauseid.c
gcc -O2 -Wall -MMD -MP     -c -o clauses.o clauses.c
gcc -O2 -Wall -MMD -MP     -c -o just.o just.c
gcc -O2 -Wall -MMD -MP     -c -o cnf.o cnf.c
gcc -O2 -Wall -MMD -MP     -c -o clausify.o clausify.c
gcc -O2 -Wall -MMD -MP     -c -o parautil.o parautil.c
gcc -O2 -Wall -MMD -MP     -c -o pindex.o pindex.c
gcc -O2 -Wall -MMD -MP     -c -o compress.o compress.c
gcc -O2 -Wall -MMD -MP     -c -o maximal.o maximal.c
gcc -O2 -Wall -MMD -MP     -c -o lindex.o lindex.c
gcc -O2 -Wall -MMD -MP     -c -o weight.o weight.c
gcc -O2 -Wall -MMD -MP     -c -o weight2.o weight2.c
gcc -O2 -Wall -MMD -MP     -c -o int_code.o int_code.c
gcc -O2 -Wall -MMD -MP     -c -o features.o features.c
gcc -O2 -Wall -MMD -MP     -c -o di_tree.o di_tree.c
gcc -O2 -Wall -MMD -MP     -c -o fastparse.o fastparse.c
gcc -O2 -Wall -MMD -MP     -c -o random.o random.c
gcc -O2 -Wall -MMD -MP     -c -o subsume.o subsume.c
gcc -O2 -Wall -MMD -MP     -c -o clause_misc.o clause_misc.c
gcc -O2 -Wall -MMD -MP     -c -o clause_eval.o clause_eval.c
gcc -O2 -Wall -MMD -MP     -c -o complex.o complex.c
gcc -O2 -Wall -MMD -MP     -c -o dollar.o dollar.c
gcc -O2 -Wall -MMD -MP     -c -o flatdemod.o flatdemod.c
gcc -O2 -Wall -MMD -MP     -c -o demod.o demod.c
gcc -O2 -Wall -MMD -MP     -c -o clash.o clash.c
gcc -O2 -Wall -MMD -MP     -c -o resolve.o resolve.c
gcc -O2 -Wall -MMD -MP     -c -o paramod.o paramod.c
gcc -O2 -Wall -MMD -MP     -c -o backdemod.o backdemod.c
gcc -O2 -Wall -MMD -MP     -c -o hints.o hints.c
gcc -O2 -Wall -MMD -MP     -c -o ac_redun.o ac_redun.c
gcc -O2 -Wall -MMD -MP     -c -o xproofs.o xproofs.c
gcc -O2 -Wall -MMD -MP     -c -o ivy.o ivy.c
gcc -O2 -Wall -MMD -MP     -c -o interp.o interp.c
gcc -O2 -Wall -MMD -MP     -c -o std_options.o std_options.c
gcc -O2 -Wall -MMD -MP     -c -o banner.o banner.c
gcc -O2 -Wall -MMD -MP     -c -o ioutil.o ioutil.c
gcc -O2 -Wall -MMD -MP     -c -o tptp_trans.o tptp_trans.c
gcc -O2 -Wall -MMD -MP     -c -o top_input.o top_input.c
gcc -O2 -Wall -MMD -MP     -c -o tptp_parse.o tptp_parse.c
gcc -O2 -Wall -MMD -MP     -c -o sine.o sine.c
gcc -O2 -Wall -MMD -MP     -c -o tstp_proof.o tstp_proof.c
ar rs libladr.a order.o clock.o nonport.o fatal.o ibuffer.o memory.o hash.o string.o strbuf.o glist.o options.o symbols.o avltree.o term.o termflag.o listterm.o tlist.o flatterm.o multiset.o termorder.o parse.o accanon.o unify.o fpalist.o fpa.o discrim.o discrimb.o discrimw.o dioph.o btu.o btm.o mindex.o basic.o attrib.o formula.o definitions.o literals.o topform.o clist.o clauseid.o clauses.o just.o cnf.o clausify.o parautil.o pindex.o compress.o maximal.o lindex.o weight.o weight2.o int_code.o features.o di_tree.o fastparse.o random.o subsume.o clause_misc.o clause_eval.o complex.o dollar.o flatdemod.o demod.o clash.o resolve.o paramod.o backdemod.o hints.o ac_redun.o xproofs.o ivy.o interp.o std_options.o banner.o ioutil.o tptp_trans.o top_input.o tptp_parse.o sine.o tstp_proof.o
ar: creating libladr.a
make[2]: Leaving directory '/kaggle/working/Prover9-LADR-2026-4F/ladr'
make[1]: Leaving directory '/kaggle/working/Prover9-LADR-2026-4F/ladr'
cd mace4.src    && make all
make[1]: Entering directory '/kaggle/working/Prover9-LADR-2026-4F/mace4.src'
cd ../ladr && make libladr.a
make[2]: Entering directory '/kaggle/working/Prover9-LADR-2026-4F/ladr'
make[2]: Leaving directory '/kaggle/working/Prover9-LADR-2026-4F/ladr'
make libmace4.a
make[2]: Entering directory '/kaggle/working/Prover9-LADR-2026-4F/mace4.src'
mace4.src: build mode changed to release, rebuilding...
gcc -O2 -Wall -MMD -MP     -c -o estack.o estack.c
gcc -O2 -Wall -MMD -MP     -c -o util.o util.c
gcc -O2 -Wall -MMD -MP     -c -o print.o print.c
print.c: In function ‘print_model_tptp’:
print.c:447:45: warning: ‘conjunct_count’ may be used uninitialized in this function []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wmaybe-uninitialized-Wmaybe-uninitialized]8;;]
  447 |         if (has_functions || conjunct_count > 0)
      |                              ~~~~~~~~~~~~~~~^~~
gcc -O2 -Wall -MMD -MP     -c -o syms.o syms.c
gcc -O2 -Wall -MMD -MP     -c -o ground.o ground.c
gcc -O2 -Wall -MMD -MP     -c -o arithmetic.o arithmetic.c
gcc -O2 -Wall -MMD -MP     -c -o select.o select.c
gcc -O2 -Wall -MMD -MP     -c -o propagate.o propagate.c
gcc -O2 -Wall -MMD -MP     -c -o mstate.o mstate.c
gcc -O2 -Wall -MMD -MP     -c -o negpropindex.o negpropindex.c
gcc -O2 -Wall -MMD -MP     -c -o negprop.o negprop.c
gcc -O2 -Wall -MMD -MP     -c -o ordercells.o ordercells.c
gcc -O2 -Wall -MMD -MP     -c -o commandline.o commandline.c
gcc -O2 -Wall -MMD -MP     -c -o msearch.o msearch.c
ar rs libmace4.a estack.o util.o print.o syms.o ground.o arithmetic.o select.o propagate.o mstate.o negpropindex.o negprop.o ordercells.o commandline.o msearch.o
ar: creating libmace4.a
make[2]: Leaving directory '/kaggle/working/Prover9-LADR-2026-4F/mace4.src'
gcc -O2 -Wall -MMD -MP     -c -o mace4.o mace4.c
gcc -O2 -Wall -MMD -MP   -static -o mace4 mace4.o libmace4.a ../ladr/libladr.a
/usr/bin/ld: ../ladr/libladr.a(nonport.o): in function `username':
nonport.c:(.text+0x10): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
codesign -s - -f mace4 2>/dev/null || true
/bin/cp -p mace4 ../bin
make[1]: Leaving directory '/kaggle/working/Prover9-LADR-2026-4F/mace4.src'
cd provers.src  && make all
make[1]: Entering directory '/kaggle/working/Prover9-LADR-2026-4F/provers.src'
cd ../ladr && make libladr
make[2]: Entering directory '/kaggle/working/Prover9-LADR-2026-4F/ladr'
make libladr.a
make[3]: Entering directory '/kaggle/working/Prover9-LADR-2026-4F/ladr'
make[3]: Leaving directory '/kaggle/working/Prover9-LADR-2026-4F/ladr'
make[2]: Leaving directory '/kaggle/working/Prover9-LADR-2026-4F/ladr'
cd ../mace4.src && make libmace4
make[2]: Entering directory '/kaggle/working/Prover9-LADR-2026-4F/mace4.src'
make libmace4.a
make[3]: Entering directory '/kaggle/working/Prover9-LADR-2026-4F/mace4.src'
make[3]: Leaving directory '/kaggle/working/Prover9-LADR-2026-4F/mace4.src'
make[2]: Leaving directory '/kaggle/working/Prover9-LADR-2026-4F/mace4.src'
provers.src: build mode changed to release, rebuilding...
gcc -O2 -Wall -MMD -MP      -c -o prover9.o prover9.c
gcc -O2 -Wall -MMD -MP      -c -o index_lits.o index_lits.c
gcc -O2 -Wall -MMD -MP      -c -o forward_subsume.o forward_subsume.c
gcc -O2 -Wall -MMD -MP      -c -o demodulate.o demodulate.c
gcc -O2 -Wall -MMD -MP      -c -o pred_elim.o pred_elim.c
gcc -O2 -Wall -MMD -MP      -c -o unfold.o unfold.c
gcc -O2 -Wall -MMD -MP      -c -o semantics.o semantics.c
gcc -O2 -Wall -MMD -MP      -c -o giv_select.o giv_select.c
gcc -O2 -Wall -MMD -MP      -c -o white_black.o white_black.c
gcc -O2 -Wall -MMD -MP      -c -o actions.o actions.c
gcc -O2 -Wall -MMD -MP      -c -o search.o search.c
search.c: In function ‘restore_fpa_ids’:
search.c:4356:11: warning: ignoring return value of ‘fscanf’ declared with attribute ‘warn_unused_result’ []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-result-Wunused-result]8;;]
 4356 |           fscanf(fp, " %u", &dummy);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~
search.c:4381:11: warning: ignoring return value of ‘fscanf’ declared with attribute ‘warn_unused_result’ []8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wunused-result-Wunused-result]8;;]
 4381 |           fscanf(fp, " %u", &dummy);
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~
gcc -O2 -Wall -MMD -MP      -c -o utilities.o utilities.c
gcc -O2 -Wall -MMD -MP      -c -o provers.o provers.c
gcc -O2 -Wall -MMD -MP      -c -o foffer.o foffer.c
gcc -O2 -Wall -MMD -MP      -c -o features.o features.c
gcc -O2 -Wall -MMD -MP      -c -o dtree.o dtree.c
gcc -O2 -Wall -MMD -MP    -static -o prover9 prover9.o index_lits.o forward_subsume.o demodulate.o pred_elim.o unfold.o semantics.o giv_select.o white_black.o actions.o search.o utilities.o provers.o foffer.o features.o dtree.o ../ladr/libladr.a -lm
/usr/bin/ld: ../ladr/libladr.a(nonport.o): in function `username':
nonport.c:(.text+0x10): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
gcc -O2 -Wall -MMD -MP      -c -o fof-prover9.o fof-prover9.c
gcc -O2 -Wall -MMD -MP    -static -o fof-prover9 fof-prover9.o index_lits.o forward_subsume.o demodulate.o pred_elim.o unfold.o semantics.o giv_select.o white_black.o actions.o search.o utilities.o provers.o foffer.o features.o dtree.o ../ladr/libladr.a -lm
/usr/bin/ld: ../ladr/libladr.a(nonport.o): in function `username':
nonport.c:(.text+0x10): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
gcc -O2 -Wall -MMD -MP      -c -o autosketches4.o autosketches4.c
gcc -O2 -Wall -MMD -MP    -static -o autosketches4 autosketches4.o index_lits.o forward_subsume.o demodulate.o pred_elim.o unfold.o semantics.o giv_select.o white_black.o actions.o search.o utilities.o provers.o foffer.o features.o dtree.o ../ladr/libladr.a -lm
/usr/bin/ld: ../ladr/libladr.a(nonport.o): in function `username':
nonport.c:(.text+0x10): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
gcc -O2 -Wall -MMD -MP      -c -o newauto.o newauto.c
gcc -O2 -Wall -MMD -MP    -static -o newauto newauto.o index_lits.o forward_subsume.o demodulate.o pred_elim.o unfold.o semantics.o giv_select.o white_black.o actions.o search.o utilities.o provers.o foffer.o features.o dtree.o ../ladr/libladr.a -lm
/usr/bin/ld: ../ladr/libladr.a(nonport.o): in function `username':
nonport.c:(.text+0x10): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
gcc -O2 -Wall -MMD -MP      -c -o newsax.o newsax.c
gcc -O2 -Wall -MMD -MP    -static -o newsax newsax.o index_lits.o forward_subsume.o demodulate.o pred_elim.o unfold.o semantics.o giv_select.o white_black.o actions.o search.o utilities.o provers.o foffer.o features.o dtree.o ../ladr/libladr.a -lm
/usr/bin/ld: ../ladr/libladr.a(nonport.o): in function `username':
nonport.c:(.text+0x10): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
gcc -O2 -Wall -MMD -MP      -c -o ladr_to_tptp.o ladr_to_tptp.c
gcc -O2 -Wall -MMD -MP    -static -o ladr_to_tptp ladr_to_tptp.o index_lits.o forward_subsume.o demodulate.o pred_elim.o unfold.o semantics.o giv_select.o white_black.o actions.o search.o utilities.o provers.o foffer.o features.o dtree.o ../ladr/libladr.a -lm
/usr/bin/ld: ../ladr/libladr.a(nonport.o): in function `username':
nonport.c:(.text+0x10): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
gcc -O2 -Wall -MMD -MP      -c -o tptp_to_ladr.o tptp_to_ladr.c
gcc -O2 -Wall -MMD -MP    -static -o tptp_to_ladr tptp_to_ladr.o index_lits.o forward_subsume.o demodulate.o pred_elim.o unfold.o semantics.o giv_select.o white_black.o actions.o search.o utilities.o provers.o foffer.o features.o dtree.o ../ladr/libladr.a -lm
/usr/bin/ld: ../ladr/libladr.a(nonport.o): in function `username':
nonport.c:(.text+0x10): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
make[1]: Leaving directory '/kaggle/working/Prover9-LADR-2026-4F/provers.src'
cd apps.src     && make all
make[1]: Entering directory '/kaggle/working/Prover9-LADR-2026-4F/apps.src'
cd ../ladr && make libladr.a
make[2]: Entering directory '/kaggle/working/Prover9-LADR-2026-4F/ladr'
make[2]: Leaving directory '/kaggle/working/Prover9-LADR-2026-4F/ladr'
gcc -O2 -Wall -MMD -MP     -c -o latfilter.o latfilter.c
gcc -O2 -Wall -MMD -MP   -static -o latfilter latfilter.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o olfilter.o olfilter.c
gcc -O2 -Wall -MMD -MP   -static -o olfilter olfilter.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o clausefilter.o clausefilter.c
gcc -O2 -Wall -MMD -MP   -static -o clausefilter clausefilter.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o idfilter.o idfilter.c
gcc -O2 -Wall -MMD -MP   -static -o idfilter idfilter.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o renamer.o renamer.c
gcc -O2 -Wall -MMD -MP   -static -o renamer renamer.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o unfast.o unfast.c
gcc -O2 -Wall -MMD -MP   -static -o unfast unfast.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o clausetester.o clausetester.c
gcc -O2 -Wall -MMD -MP   -static -o clausetester clausetester.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o rewriter.o rewriter.c
gcc -O2 -Wall -MMD -MP   -static -o rewriter rewriter.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o isofilter0.o isofilter0.c
gcc -O2 -Wall -MMD -MP   -static -o isofilter0 isofilter0.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o isofilter.o isofilter.c
gcc -O2 -Wall -MMD -MP   -static -o isofilter isofilter.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o isofilter2.o isofilter2.c
gcc -O2 -Wall -MMD -MP   -static -o isofilter2 isofilter2.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o dprofiles.o dprofiles.c
gcc -O2 -Wall -MMD -MP   -static -o dprofiles dprofiles.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o interpfilter.o interpfilter.c
gcc -O2 -Wall -MMD -MP   -static -o interpfilter interpfilter.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o upper-covers.o upper-covers.c
gcc -O2 -Wall -MMD -MP   -static -o upper-covers upper-covers.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o miniscope.o miniscope.c
gcc -O2 -Wall -MMD -MP   -static -o miniscope miniscope.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o interpformat.o interpformat.c
gcc -O2 -Wall -MMD -MP   -static -o interpformat interpformat.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o prooftrans.o prooftrans.c
gcc -O2 -Wall -MMD -MP   -static -o prooftrans prooftrans.o ../ladr/libladr.a
/usr/bin/ld: ../ladr/libladr.a(nonport.o): in function `username':
nonport.c:(.text+0x10): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
gcc -O2 -Wall -MMD -MP     -c -o mirror-flip.o mirror-flip.c
gcc -O2 -Wall -MMD -MP   -static -o mirror-flip mirror-flip.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o perm3.o perm3.c
gcc -O2 -Wall -MMD -MP   -static -o perm3 perm3.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o sigtest.o sigtest.c
gcc -O2 -Wall -MMD -MP   -static -o sigtest sigtest.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o directproof.o directproof.c
gcc -O2 -Wall -MMD -MP   -static -o directproof directproof.o ../ladr/libladr.a
/usr/bin/ld: ../ladr/libladr.a(nonport.o): in function `username':
nonport.c:(.text+0x10): warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
gcc -O2 -Wall -MMD -MP     -c -o test_clause_eval.o test_clause_eval.c
gcc -O2 -Wall -MMD -MP   -static -o test_clause_eval test_clause_eval.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o test_complex.o test_complex.c
gcc -O2 -Wall -MMD -MP   -static -o test_complex test_complex.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o complex.o complex.c
gcc -O2 -Wall -MMD -MP   -static -o complex complex.o ../ladr/libladr.a
gcc -O2 -Wall -MMD -MP     -c -o gen_trc_defs.o gen_trc_defs.c
gcc -O2 -Wall -MMD -MP   -static -o gen_trc_defs gen_trc_defs.o ../ladr/libladr.a
make[1]: Leaving directory '/kaggle/working/Prover9-LADR-2026-4F/apps.src'
/bin/cp -p utilities/* bin

**** Now try 'make test1'. ****

/kaggle/working

In [2]:
!pip install pandas \
            seaborn \
            matplotlib \
            nltk \
            regex \
            torch \
            datasets \
            transformers \
            peft \
            nltk

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.3.3)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: regex in /usr/local/lib/python3.12/dist-packages (2025.11.3)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.8.3)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: peft in /usr/local/lib/python3.12/dist-packages (0.18.1)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch) (3.24.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2026.2.0)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.3.5)
Requirement already satisfied: pyarrow>=21.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (23.0.1)
Requirement already satisfied: dill<0.4.2,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.4.1)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.20 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: huggingface-hub<2.0,>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.4.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (5.9.5)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from peft) (1.12.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.3.0)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=0.25.0->datasets) (1.5.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers) (0.24.1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.2.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim->transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim->transformers) (0.1.2)

In [3]:
import torch
import json
from datasets import Dataset,DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    EarlyStoppingCallback
)
from peft import LoraConfig, get_peft_model, PeftModel
from torch.nn import CrossEntropyLoss

import random
import numpy as np

import nltk
from nltk.sem.logic import LogicParser
from nltk.inference import Prover9
import regex as re  
from typing import Optional
import os
import gc
import copy
from collections import Counter
from torch.utils.data import DataLoader
from tqdm import tqdm

In [4]:
import warnings

# Chặn toàn bộ UserWarning phát ra từ module save_and_load của thư viện peft
warnings.filterwarnings(
    "ignore", 
    category=UserWarning, 
    module="peft.utils.save_and_load"
)

In [5]:
class ManualDataset(torch.utils.data.Dataset):
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        item["fol_premises"] = item.get("fol_premises", None)
        item["fol_conclusion"] = item.get("fol_conclusion", None)
        return {
            "id": item["id"],
            "nat_premises": item["nat_premises"],
            "fol_premises":  "" if item["fol_premises"] is None else item["fol_premises"],
            "nat_conclusion": item["nat_conclusion"],
            "fol_conclusion": "" if item["fol_conclusion"] is None else item["fol_conclusion"],
            "label": item["label"]
        }


class FOLModel:
    def __init__(
        self,
        model_name: str = "deepseek-ai/DeepSeek-R1-Distill-Qwen-7B",
        output_dir: str = "/kaggle/working/fol_model",
        adapter_dir: str = "/kaggle/input/models/ductri0981/fol-model/transformers/default/2",
        max_length: int = 768,
        local_files_only=True
    ):
        self.model_name = model_name
        self.output_dir = output_dir
        self.max_length = max_length
        self.adapter_dir = adapter_dir
        
        #Load tokenizer
        print("Loading tokenizer...")
        self.tokenizer = AutoTokenizer.from_pretrained(
            model_name,
            trust_remote_code=True,
            local_files_only=local_files_only
        )

        #Load base model.
        print("Loading model...")
        self.model = AutoModelForCausalLM.from_pretrained(
            model_name,
            dtype=torch.float16,
            device_map={"": 0},
            trust_remote_code=True,
            local_files_only=True
        )
        self.tokenizer.pad_token = self.tokenizer.eos_token
        self.model.config.use_cache = False
        self.tokenizer.padding_side = "left"
        self._load_or_init_lora()
        
    def _init_lora(self):
        print("Initializing LoRA...")
    
        lora_config = LoraConfig(
            r=16,
            lora_alpha=32,
            target_modules=[
                "q_proj", "k_proj", "v_proj", "o_proj",
                "gate_proj", "up_proj", "down_proj"
            ],
            lora_dropout=0.05,
            bias="none",
            task_type="CAUSAL_LM",
        )
    
        self.model = get_peft_model(self.model, lora_config)
        self.model.print_trainable_parameters()

    def _load_or_init_lora(self):
        if isinstance(self.model, PeftModel):
            print("Resetting to base model...")
            self.model = AutoModelForCausalLM.from_pretrained(
                self.model_name,
                dtype=torch.float16,
                device_map={"": 0},
                trust_remote_code=True,
                local_files_only=True
            )
        
        if os.path.exists(self.adapter_dir):
            print("Loading existing LoRA adapter...")

            self.model = PeftModel.from_pretrained(
                self.model,
                self.adapter_dir,
                is_trainable=True,
                local_files_only=True
            )
        else:
            print("No adapter found → initializing new LoRA")
            self._init_lora()

    def _prompt_template(self, data_example, is_predict=False):
        premises_list = [
            s.strip() for s in data_example['nat_premises'].split('.') if s.strip()
        ]
        formatted_premises = "\n".join(
            [f"{i+1}. {s}." for i, s in enumerate(premises_list)]
        )
        formatted_all = formatted_premises + f"\n{len(premises_list)+1}. {data_example['nat_conclusion']}"
        output_part = "" if is_predict else f"{data_example['fol_premises']}\n{data_example['fol_conclusion']}"
        prompt = f"""### Role
You are a precise Natural Language to First-Order Logic (FOL) translator. Your task is to perform a direct, line-by-line mapping of sentences into formal logic.

### Logical Symbols
Strictly use these symbols:
- Universal: ∀
- Existential: ∃
- Conjunction: ∧
- Disjunction: ∨
- Exclusive Or: ⊕
- Negation: ¬
- Implication: →
- Equivalence: ↔

### Strict Constraints
1. **One-to-One Parity**: The number of FOL expressions in the output must exactly match the number of sentences in the Natural Language input. 
2. **Line Separation**: Each FOL expression must be placed on a new line. Do not use any other delimiters or numbering.
3. **Predicate Consistency**: 
   - Use a single, consistent name for each property or relation. 
   - Do not use synonyms (e.g., if you use "Student(x)", do not use "is_student(x)" or "IsStudent(x)" elsewhere).
   - Prefer concise noun-based or verb-based naming (e.g., "Teacher(x)", "Loves(x, y)").
4. **No Metadata**: Output ONLY the FOL expressions. No explanations, no thought process, and no introductory remarks.

Now apply the rules strictly to the following input:

### Input:
{formatted_all}

### Output:
{output_part}
"""
        return {"text": prompt}
        
    def _tokenize(self, data):
        prompt = data['text']
        tokenized = self.tokenizer(
            prompt,
            padding="max_length",
            truncation=True,
            max_length=self.max_length
        )
        labels = tokenized["input_ids"].copy()
        # Only predict next token after "output prompt"
        output_start = prompt.index("### Output:")
        output_tokens = self.tokenizer(prompt[:output_start])["input_ids"]
        #Label from start to output tokens => mask with -100.
        labels[:len(output_tokens)] = [-100] * len(output_tokens)
        tokenized["labels"] = labels
        return tokenized

    def prepare_sample(self, data_example):
        """Tiền xử lý 1 mẫu dữ liệu hoàn chỉnh thành các Token ID trước khi đưa vào finetune_set"""
        prompt_dict = self._prompt_template(data_example)
        tokenized_dict = self._tokenize(prompt_dict)
        
        # Chỉ trả về các trường cần thiết để huấn luyện, tiết kiệm bộ nhớ RAM
        return {
            "input_ids": tokenized_dict["input_ids"],
            "attention_mask": tokenized_dict["attention_mask"],
            "labels": tokenized_dict["labels"]
        }
    in
    def train(
        self,
        train_data: ManualDataset,
        epochs: int = 1,
        batch_size: int = 4,
        learning_rate: float = 1e-4,
        gradient_accumulation_steps=1
    ):
        
        print("Loading finetuning data...")
        train_data = Dataset.from_list(train_data.data)
        train_data.set_format(type="torch", columns=["input_ids", "attention_mask", "labels"])

        training_args = TrainingArguments(
            output_dir=self.output_dir,
            
            per_device_train_batch_size=batch_size,
            per_device_eval_batch_size=batch_size,
            gradient_accumulation_steps=gradient_accumulation_steps,
            num_train_epochs=epochs,
            learning_rate=learning_rate,
            
            logging_steps=10,
            report_to="none",

            bf16=True,
            tf32=True,
            dataloader_num_workers=4,

            save_total_limit=1
        )

        trainer = Trainer(
            model=self.model,
            args=training_args,
            train_dataset=train_data,
        )
        
        trainer.train()
        
        del trainer
        gc.collect()
        torch.cuda.empty_cache()
        
    def predict(self, dataset: ManualDataset, max_new_tokens: int = 768, num_outputs: int = 10):
        loader = DataLoader(
            dataset,
            batch_size=32,
            shuffle=False,
        )
        self.model.eval()
        data = []
    
        with torch.no_grad():
            loop = tqdm(loader)
    
            for batch in loop:
    
                ids = batch["id"]
                premises = batch["nat_premises"]
                conclusions = batch["nat_conclusion"]
                labels = batch["label"]
    
                # ensure list
                if isinstance(premises, str):
                    premises = [premises]
                    conclusions = [conclusions]
                    ids = [ids]
                    labels = [labels]
    
                batch_size = len(premises)
    
                # 1. build prompts correctly
                prompts = []
                for i in range(batch_size):
    
                    sample = {
                        "nat_premises": premises[i],
                        "nat_conclusion": conclusions[i]
                    }
    
                    prompts.append(self._prompt_template(sample, is_predict=True)["text"])
    
                # 2. tokenize batch
                inputs = self.tokenizer(
                    prompts,
                    return_tensors="pt",
                    padding=True,
                    truncation=True,
                    max_length=self.max_length
                ).to(self.model.device)
    
                # 3. generate
                outputs = self.model.generate(
                    **inputs,
                    max_new_tokens=max_new_tokens,
                    do_sample=True,
                    temperature=1.0,
                    min_p=0.05,
                    num_return_sequences=num_outputs,
                    pad_token_id=self.tokenizer.eos_token_id
                )
    
                # 4. decode
                decoded_outputs = self.tokenizer.batch_decode(
                    outputs,
                    skip_special_tokens=True
                )
    
                # 5. reshape results
                for i in range(batch_size):
    
                    sample_outputs = []
    
                    for j in range(num_outputs):
    
                        idx = i * num_outputs + j
                        text = decoded_outputs[idx]
    
                        if "### Output:" in text:
                            text = text.split("### Output:")[-1].strip()
                        else:
                            text = text[len(prompts[i]):].strip()
    
                        sample_outputs.append(text)
    
                    data.append({
                        "id": ids[i],
                        "natural": premises[i] + "\n" + conclusions[i],
                        "predictions": [
                            {"fol": fol, "label": None}
                            for fol in sample_outputs
                        ],
                        "label": labels[i]
                    })
    
        return data

In [6]:
class Engine:
    def __init__(self, prover9_path='C:\\Program Files (x86)\\Prover9-Mace4\\bin-win32'):
        self.parser = LogicParser()
        self.prover9_path = prover9_path
        self.prover = Prover9()
        self.prover.config_prover9(prover9_path)

    def _transform_xor(self, text):
        """
        Transform A ⊕ B to ¬(A ⟷ B)
        """
        while '⊕' in text:
            idx = text.find('⊕')
            
            # Find left component
            lhs_end = idx
            while lhs_end > 0 and text[lhs_end-1].isspace():
                lhs_end -= 1
                
            curr = lhs_end - 1
    
            if text[curr] == ')':
                balance = 0
                while curr >= 0:
                    if text[curr] == ')': balance += 1
                    elif text[curr] == '(': balance -= 1
                    curr -= 1
                    if balance == 0: break
                while curr >= 0 and (text[curr].isalnum() or text[curr] == '_'):
                    curr -= 1
                lhs_start = curr + 1
            else:
                while curr >= 0 and (text[curr].isalnum() or text[curr] == '_'):
                    curr -= 1
                lhs_start = curr + 1
                
            lhs = text[lhs_start:lhs_end]
    
            # Find right component
            rhs_start = idx + 1
            while rhs_start < len(text) and text[rhs_start].isspace():
                rhs_start += 1
                
            curr = rhs_start
            if text[curr].isalnum() or text[curr] == '_':
                while curr < len(text) and (text[curr].isalnum() or text[curr] == '_'):
                    curr += 1
                if curr < len(text) and text[curr] == '(':
                    balance = 0
                    while curr < len(text):
                        if text[curr] == '(': balance += 1
                        elif text[curr] == ')': balance -= 1
                        curr += 1
                        if balance == 0: break
                rhs_end = curr
            elif text[curr] == '(':
                balance = 0
                while curr < len(text):
                    if text[curr] == '(': balance += 1
                    elif text[curr] == ')': balance -= 1
                    curr += 1
                    if balance == 0: break
                rhs_end = curr
            else:
                rhs_end = curr + 1
                
            rhs = text[rhs_start:rhs_end]
    
            # Transform XOR
            new_expression = f"¬({lhs} ⟷ {rhs})"
            text = text[:lhs_start] + new_expression + text[rhs_end:]
    
        return text
    
    def _translate_fol(self, fol_text: str):
        # Transform XOR
        fol_text = self._transform_xor(fol_text)
        
        # '-' --> '_'
        fol_text = re.sub(r'(?<=[a-zA-Z0-9])-(?=[a-zA-Z0-9])', '_', fol_text)

        replacements = {
            '∀': 'all ', 
            '∃': 'exists ',
            '∧': '&', 
            '∨': '|',
            '⊕': '^',
            '¬': '-',
            '→': '->', 
            '⟷': '<->',
            '↔': '<->'
        }
        for k, v in replacements.items():
            fol_text = fol_text.replace(k, v)

        # Add dot: "all x (P(x))" --> "all x. (P(x))"
        fol_text = re.sub(r'(all|exists)\s+([a-z0-9]+)\s*', r'\1 \2. ', fol_text)

        # Fix prover9 constants name (eg: "yuri" -> "c_yuri")
        words = re.findall(r'\b[a-z][a-zA-Z0-9_]*\b', fol_text)
        reserved_words = {'all', 'exists', 'u', 'v', 'w', 'x', 'y', 'z'}
        
        for w in set(words):
            if w not in reserved_words:
                fol_text = re.sub(fr'\b{w}\b', f'c_{w}', fol_text)
        return fol_text


    def _is_valid_fol(self, fol_list):
        try:
            for line in fol_list:
                if line.strip():
                    self.parser.parse(line)
            return True
        except Exception:
            return False

    def _check_conclusion(self, premises, conclusion):
        '''
        This function is the engine. It checks whether the conclusion is True/False/Uncertain based on the list of premises.
        Args:
            premises: list[str]
            conclusion: str
        Returns: 
            str ("True"/"False"/"Uncertain")
        '''
        # Read fol strings
        translated_premises = [self._translate_fol(p) for p in premises]
        translated_conclusion = self._translate_fol(conclusion)

        if (not self._is_valid_fol(translated_premises) or not self._is_valid_fol([translated_conclusion])):
            error_msg = f"Invalid FOL syntax detected!"
            raise ValueError(error_msg)
        
        try:
            parsed_premises = [self.parser.parse(p) for p in translated_premises]
            parsed_conclusion = self.parser.parse(translated_conclusion)
        except Exception as e:
            raise f"Error: {e}"

        # Check conclusion
        if self.prover.prove(parsed_conclusion, []):
            raise Exception("Error: The conclusion itself is True!")
        elif self.prover.prove(parsed_conclusion.negate(), []):
            raise Exception("Error: The conclusion itself is False!")
        elif not self.prover.prove(None, parsed_premises):
            is_true = self.prover.prove(parsed_conclusion, parsed_premises)
            if is_true:
                return "True"

            is_false = self.prover.prove(parsed_conclusion.negate(), parsed_premises)
            if is_false:
                return "False"

            return "Uncertain"
        else: 
            raise Exception("Error: The premises are inconsistent!")
    
    def check_conclusion(self, data):
        fol_list = data["predictions"]
        new_fol_list = []
        for fol in fol_list:
            try:
                premises = fol["fol"].split("\n")[:-1]
                conclusion = fol["fol"].split("\n")[-1]
                result = self._check_conclusion(premises, conclusion)

                if result == "True":
                    fol["label"] = "True"
                elif result == "False":   # FIX 2
                    fol["label"] = "False"
                else:
                    fol["label"] = "Uncertain"
                new_fol_list.append(fol)
            except Exception as e:
                # print(e)
                continue

        data["predictions"] = new_fol_list
        return data

In [7]:
def lv_distance(s1, s2):
    if len(s1) < len(s2):
        return lv_distance(s2, s1)

    if len(s2) == 0:
        return len(s1)

    previous_row = range(len(s2) + 1)
    for i, c1 in enumerate(s1):
        current_row = [i + 1]
        for j, c2 in enumerate(s2):
            insertions = previous_row[j + 1] + 1
            deletions = current_row[j] + 1
            substitutions = previous_row[j] + (c1 != c2)
            current_row.append(min(insertions, deletions, substitutions))
        previous_row = current_row
    
    return previous_row[-1]

class DataFilter:
    def __init__(self):
        self.duplicate_count = 0
        self.syntax_error_count = 0
        self.length_ratio_count = 0
    
    def _is_valid_syntax(self, fol_str: str) -> bool:
        if not fol_str:
            return False
            
        stack = []
        matching_bracket = {')': '(', ']': '[', '}': '{'}
        
        for char in fol_str:                   
            if char in matching_bracket.values():
                stack.append(char)
            elif char in matching_bracket.keys():
                if not stack or stack.pop() != matching_bracket[char]:
                    return False

        return len(stack) == 0
    
    
    def _is_valid_length_ratio(self, nat_str: str, fol_str: str, lowerbound_ratio: float=0.5, upperbound_ratio: float=2.0) -> bool:
        nat_length = len(nat_str)
        if nat_length == 0:
            return False
    
        fol_length = len(fol_str)
        ratio = fol_length / nat_length
        
        return lowerbound_ratio <= ratio <= upperbound_ratio


    def _update_names(self, fol, ratio_threshold=1/3):
        pattern = r'(\w+)\('
        matches = re.findall(pattern, fol)
    
        counts = Counter(matches)
        all_names = list(set(matches))
    
        single_names = [name for name, count in counts.items() if count == 1]
    
        update_names = {}
    
        for n1 in single_names:
            for n2 in all_names:
                if n2 in single_names and len(n2) > len(n1):
                    continue
                if n1 != n2 and lv_distance(n1, n2) <= ratio_threshold * max(len(n1), len(n2)):
                    update_names[n1] = n2
    
        return update_names
    
    
    def filter(self, entry: dict, lowerbound_ratio:float=0.5, upperbound_ratio:float=2.0) -> dict:
        valid_predictions = []
        nat_str = entry.get("natural", "")
        
        natural_text = entry.get("natural", "").strip()
        sentences = [s for s in natural_text.split('.') if s.strip()]
        nat_length = len(sentences)

        for pred in entry.get("predictions", []):
            fol = pred.get("fol", "")
            
            # Validate syntax (bracket balancing)
            if not self._is_valid_syntax(fol):
                self.syntax_error_count += 1
                continue
            
            premise_list = [p.strip() for p in fol.split('\n') if p.strip()]
            conclusion = premise_list[-1]
            
            premise_list = list(dict.fromkeys(premise_list[:-1]))

            # if len(premise_list) != (nat_length - 1):
            #     self.duplicate_count += 1
            #     continue
            
            # Check for length ratio
            if not self._is_valid_length_ratio(nat_str, fol, lowerbound_ratio, upperbound_ratio):
                self.length_ratio_count += 1
                continue

            valid_fol = "\n".join(premise_list + [conclusion])
            update = self._update_names(valid_fol)
            for key, value in update.items():
                pattern = fr'(?<![a-zA-Z0-9]){key}\('
                valid_fol = re.sub(pattern, value + "(", valid_fol)

            valid_predictions.append({'fol': valid_fol, 'label': None})
            
        filtered_element = entry.copy()
        filtered_element["predictions"] = valid_predictions

        return filtered_element

def filter2_pred(fol_predictions, ground_truth, threshold: float = 0.5):
    if len(fol_predictions) == 0:
        return None

    count = {"True": 0, "False": 0, "Uncertain": 0}

    for prediction in fol_predictions:
        count[prediction["label"]] += 1

    if count[ground_truth] / len(fol_predictions) > threshold:
        return True
    return False

def filter2(fol_predictions, ground_truth, threshold: float = 0.5):
    if len(fol_predictions) == 0:
        return None

    count = {"True": 0, "False": 0, "Uncertain": 0}

    for prediction in fol_predictions:
        count[prediction["label"]] += 1

    if count[ground_truth] / len(fol_predictions) > threshold:
        positive_sample = [prediction for prediction in fol_predictions if prediction["label"] == ground_truth]
        negative_sample = [prediction for prediction in fol_predictions if prediction["label"] != ground_truth]
        return positive_sample, negative_sample

    return None

In [8]:
!cp -rf /kaggle/input/models/ductri0981/fol-model/transformers/default/2 /kaggle/working/lora_adapter

In [9]:
class Pipeline:
    def __init__(self, fol_model):
        self.fol_model = fol_model
        self.filter_1 = DataFilter()
        self.engine = Engine(prover9_path="/kaggle/working/Prover9-LADR-2026-4F/bin")
    
    def get_data(self, file_path):
        with open(file_path, "r", encoding="utf-8") as f:
            dataset = json.load(f)
        return dataset

    def __save_file_prediction(self, predictions, file_name="predictions.json"):
        with open(file_name, "w", encoding="utf-8") as f:
            json.dump(predictions, f, indent=4, ensure_ascii=False)
            
    def train(self, train_set_path,
              valid_set_path,
              silver_set_path,
              new_train_set_path,
              folio_set_path,
              batch_pop=32,
              max_steps=3, batchsize=4, previous_step=1):

        best_accuracy = 0.0

        train_set = self.get_data(train_set_path)
        valid_set = self.get_data(valid_set_path)
        
        finetune_set = []
        silver_set = []

        folio_set = self.get_data(folio_set_path)
        for i in range(len(folio_set)):
            processed_tensor_sample = self.fol_model.prepare_sample(folio_set[i])
            finetune_set.append({
                "item": processed_tensor_sample,
                "usage_count": 0
            })
            silver_set.append(folio_set[i])

        print(f"Bắt đầu quy trình tự học với tổng {len(train_set)} mẫu trong dataset gốc.")

        for step in range(max_steps):
            print(f"\n========== STEP {step + 1 + previous_step}/{max_steps + previous_step} ==========")

            if len(train_set) == 0:
                print("Đã lấy hết dữ liệu từ train_set ban đầu. Tiếp theo chỉ thực hiện finetune.")
            else:
                # Lấy batchsize mẫu từ trên xuống và xóa khỏi train_set
                current_batch_size = min(batch_pop, len(train_set))
                batch_data = train_set[:current_batch_size]
                train_set = train_set[current_batch_size:]
    
                # Mô hình dự đoán
                batch_data = ManualDataset(batch_data)
                predicted_batch = self.fol_model.predict(batch_data)
                # predicted_batch = self.format_predict_dataset(batch_data)
    
                for original_data, pred_data in zip(batch_data, predicted_batch):
                    is_success = False
                    
                    pred_data = self.filter_1.filter(pred_data)
                    pred_data = self.engine.check_conclusion(pred_data)
                    
                    result_filter2 = filter2(pred_data['predictions'], pred_data["label"])
                    if result_filter2 is not None:
                        positive_fol, _ = result_filter2
                        chosen_pred = positive_fol[0]
    
                        nat_prem, nat_conc = pred_data["natural"].split("\n")
    
                        formatted_sample = {
                            "id": pred_data["id"],
                            "nat_premises": nat_prem,
                            "nat_conclusion": nat_conc,
                            "fol_premises": '\n'.join(chosen_pred['fol'].split('\n')[:-1]),
                            "fol_conclusion": chosen_pred['fol'].split('\n')[-1],
                            "label": pred_data["label"]
                        }
    
                        silver_set.append(formatted_sample)
    
                        processed_tensor_sample = self.fol_model.prepare_sample(formatted_sample)
                        finetune_set.append({
                            "item": processed_tensor_sample, # Đã là input_ids, attention_mask, labels
                            "usage_count": 0
                        })
                        
                        is_success = True
    
                    if not is_success:
                        train_set.append(original_data)
    
                print(f"Kích thước finetune_set hiện tại: {len(finetune_set)}")
    
                # Huấn luyện bằng dữ liệu từ finetune_set
                if len(finetune_set) >= batch_pop:
                    weights = np.array([1.0 / (sample["usage_count"] + 1) for sample in finetune_set])
                    probs = weights / weights.sum() # Chuẩn hóa để tổng xác suất = 1.0
    
                    sampled_indices = np.random.choice(
                        len(finetune_set), 
                        size=batch_pop, 
                        replace=False, 
                        p=probs
                    )
    
                    train_batch = []
                    for idx in sampled_indices:
                        finetune_set[idx]["usage_count"] += 1
                        train_batch.append(finetune_set[idx]["item"])
    
                    # print(f"Bắt đầu huấn luyện mô hình với {batchsize} mẫu từ finetune_set...")
                    train_batch = ManualDataset(train_batch)
                    self.fol_model.train(
                        train_data=train_batch,
                        batch_size=batchsize
                    )
                else:
                    print("Chưa đủ dữ liệu trong finetune_set để tạo batch huấn luyện. Chuyển sang step tiếp theo...")

            # 50 steps valid một lần, cũng như lưu silver_data và new_train_set một lần
            if step % 50 == 0:
                if len(silver_set) > 0:
                    with open(silver_set_path, "w", encoding="utf-8") as f:
                        json.dump(silver_set, f, ensure_ascii=False, indent=4)
                    print(f"Đã lưu/cập nhật {len(silver_set)} mẫu vào {silver_set_path}")

                with open(new_train_set_path, "w", encoding="utf-8") as f:
                    json.dump(train_set, f, ensure_ascii=False, indent=4)
                print(f"Đã cập nhật new_train_set vào {new_train_set_path}")
                
                # Valid thủ công ở đây
                count_correct = 0
                valid_set = ManualDataset(valid_set)
                predictions = self.fol_model.predict(valid_set, num_outputs=10)
                # predictions = self.format_predict_dataset(valid_set, num_outputs=10)
                # self.__save_file_prediction(predictions)
                filtered_predictions = []
                for prediction in predictions:
                    prediction = self.filter_1.filter(prediction)
                    prediction = self.engine.check_conclusion(prediction)
                    filtered_predictions.append(prediction)
                    count_correct += (filter2(prediction['predictions'], prediction["label"]) is not None)
                self.__save_file_prediction(filtered_predictions)
                accuracy = count_correct / len(predictions)
                print("Validation accuracy:", accuracy)
                if accuracy > best_accuracy or accuracy == 1:
                    self.fol_model.model.save_pretrained(self.fol_model.adapter_dir)
                    self.fol_model.tokenizer.save_pretrained(self.fol_model.adapter_dir)
                    best_accuracy = accuracy

In [10]:
fol_model = FOLModel(
    model_name="/kaggle/input/models/ductri0981/deepseek-model/transformers/default/3/deepseek_model",
    adapter_dir="/kaggle/working/lora_adapter",
    local_files_only=True
)

Loading tokenizer...
Loading model...

Loading weights:   0%|          | 0/339 [00:00<?, ?it/s]

Loading existing LoRA adapter...

In [ ]:
pipeline = Pipeline(fol_model=fol_model)
pipeline.train(
    train_set_path="/kaggle/input/datasets/ductri0981/neurosymbolic-dataset/train_without_fol.json",
    valid_set_path="/kaggle/input/datasets/ductri0981/neurosymbolic-dataset/valid_without_fol.json",
    silver_set_path="/kaggle/working/silver_data.json",
    new_train_set_path="/kaggle/working/new_train_set.json",
    folio_set_path="/kaggle/input/datasets/ductri0981/neurosymbolic-dataset/folio_train.json",
    batch_pop=32,
    max_steps=201,
    batchsize=8,
    previous_step=0
)

Bắt đầu quy trình tự học với tổng 4199 mẫu trong dataset gốc.

========== STEP 1/201 ==========

100%|██████████| 1/1 [02:52<00:00, 172.05s/it]

Kích thước finetune_set hiện tại: 873
Loading finetuning data...

Đã lưu/cập nhật 873 mẫu vào /kaggle/working/silver_data.json
Đã cập nhật new_train_set vào /kaggle/working/new_train_set.json

100%|██████████| 2/2 [00:55<00:00, 27.97s/it]

Validation accuracy: 0.775

========== STEP 2/201 ==========

100%|██████████| 1/1 [02:51<00:00, 171.48s/it]

Kích thước finetune_set hiện tại: 898
Loading finetuning data...

========== STEP 3/201 ==========

100%|██████████| 1/1 [02:53<00:00, 173.47s/it]

Kích thước finetune_set hiện tại: 913
Loading finetuning data...

========== STEP 4/201 ==========

100%|██████████| 1/1 [00:40<00:00, 40.33s/it]

Kích thước finetune_set hiện tại: 926
Loading finetuning data...

========== STEP 5/201 ==========

100%|██████████| 1/1 [02:54<00:00, 174.24s/it]

Kích thước finetune_set hiện tại: 941
Loading finetuning data...

========== STEP 6/201 ==========

100%|██████████| 1/1 [02:55<00:00, 175.53s/it]

Kích thước finetune_set hiện tại: 956
Loading finetuning data...

========== STEP 7/201 ==========

100%|██████████| 1/1 [02:55<00:00, 175.75s/it]

Kích thước finetune_set hiện tại: 974
Loading finetuning data...

========== STEP 8/201 ==========

100%|██████████| 1/1 [02:56<00:00, 176.39s/it]

Kích thước finetune_set hiện tại: 994
Loading finetuning data...

========== STEP 9/201 ==========

100%|██████████| 1/1 [02:58<00:00, 178.14s/it]

Kích thước finetune_set hiện tại: 1009
Loading finetuning data...

========== STEP 10/201 ==========

100%|██████████| 1/1 [02:58<00:00, 178.34s/it]

Kích thước finetune_set hiện tại: 1027
Loading finetuning data...

========== STEP 11/201 ==========

100%|██████████| 1/1 [02:58<00:00, 178.53s/it]

Kích thước finetune_set hiện tại: 1040
Loading finetuning data...

Đã lưu/cập nhật 1040 mẫu vào /kaggle/working/silver_data.json
Đã cập nhật new_train_set vào /kaggle/working/new_train_set.json

100%|██████████| 2/2 [01:11<00:00, 35.75s/it]

Validation accuracy: 0.75

========== STEP 12/201 ==========

100%|██████████| 1/1 [03:00<00:00, 180.30s/it]

Kích thước finetune_set hiện tại: 1048
Loading finetuning data...

========== STEP 13/201 ==========

100%|██████████| 1/1 [03:00<00:00, 180.86s/it]

Kích thước finetune_set hiện tại: 1061
Loading finetuning data...

========== STEP 14/201 ==========

100%|██████████| 1/1 [03:00<00:00, 180.12s/it]

Kích thước finetune_set hiện tại: 1077
Loading finetuning data...

========== STEP 15/201 ==========

100%|██████████| 1/1 [03:01<00:00, 181.53s/it]

Kích thước finetune_set hiện tại: 1088
Loading finetuning data...

========== STEP 16/201 ==========

100%|██████████| 1/1 [03:01<00:00, 181.31s/it]

Kích thước finetune_set hiện tại: 1101
Loading finetuning data...

========== STEP 17/201 ==========

100%|██████████| 1/1 [03:02<00:00, 182.56s/it]

Kích thước finetune_set hiện tại: 1110
Loading finetuning data...

========== STEP 18/201 ==========

100%|██████████| 1/1 [03:03<00:00, 183.34s/it]

Kích thước finetune_set hiện tại: 1121
Loading finetuning data...

========== STEP 19/201 ==========

100%|██████████| 1/1 [03:03<00:00, 183.15s/it]

Kích thước finetune_set hiện tại: 1134
Loading finetuning data...

========== STEP 20/201 ==========

100%|██████████| 1/1 [03:03<00:00, 183.94s/it]

Kích thước finetune_set hiện tại: 1149
Loading finetuning data...

========== STEP 21/201 ==========

100%|██████████| 1/1 [03:03<00:00, 183.94s/it]

Kích thước finetune_set hiện tại: 1164
Loading finetuning data...

Đã lưu/cập nhật 1164 mẫu vào /kaggle/working/silver_data.json
Đã cập nhật new_train_set vào /kaggle/working/new_train_set.json

100%|██████████| 2/2 [03:09<00:00, 94.95s/it]

Validation accuracy: 0.7

========== STEP 22/201 ==========

100%|██████████| 1/1 [03:08<00:00, 188.85s/it]

Kích thước finetune_set hiện tại: 1173
Loading finetuning data...

========== STEP 23/201 ==========

100%|██████████| 1/1 [03:03<00:00, 183.75s/it]

Kích thước finetune_set hiện tại: 1180
Loading finetuning data...

========== STEP 24/201 ==========

100%|██████████| 1/1 [03:05<00:00, 185.31s/it]

Kích thước finetune_set hiện tại: 1194
Loading finetuning data...

========== STEP 25/201 ==========

100%|██████████| 1/1 [03:06<00:00, 186.48s/it]

Kích thước finetune_set hiện tại: 1207
Loading finetuning data...

========== STEP 26/201 ==========

100%|██████████| 1/1 [03:05<00:00, 185.10s/it]

Kích thước finetune_set hiện tại: 1215
Loading finetuning data...

========== STEP 27/201 ==========

100%|██████████| 1/1 [03:06<00:00, 186.87s/it]

Kích thước finetune_set hiện tại: 1230
Loading finetuning data...

========== STEP 28/201 ==========

100%|██████████| 1/1 [03:06<00:00, 186.87s/it]

Kích thước finetune_set hiện tại: 1242
Loading finetuning data...

========== STEP 29/201 ==========

100%|██████████| 1/1 [03:07<00:00, 187.27s/it]

Kích thước finetune_set hiện tại: 1250
Loading finetuning data...

========== STEP 30/201 ==========

100%|██████████| 1/1 [03:07<00:00, 187.27s/it]

Kích thước finetune_set hiện tại: 1261
Loading finetuning data...

========== STEP 31/201 ==========

100%|██████████| 1/1 [03:08<00:00, 188.65s/it]

Kích thước finetune_set hiện tại: 1276
Loading finetuning data...

Đã lưu/cập nhật 1276 mẫu vào /kaggle/working/silver_data.json
Đã cập nhật new_train_set vào /kaggle/working/new_train_set.json

100%|██████████| 2/2 [01:19<00:00, 39.55s/it]

Validation accuracy: 0.725

========== STEP 32/201 ==========

100%|██████████| 1/1 [03:08<00:00, 188.85s/it]

Kích thước finetune_set hiện tại: 1293
Loading finetuning data...

========== STEP 33/201 ==========

100%|██████████| 1/1 [03:06<00:00, 186.22s/it]

Kích thước finetune_set hiện tại: 1299
Loading finetuning data...

========== STEP 34/201 ==========

100%|██████████| 1/1 [03:06<00:00, 186.28s/it]

Kích thước finetune_set hiện tại: 1306
Loading finetuning data...

========== STEP 35/201 ==========

100%|██████████| 1/1 [03:08<00:00, 188.44s/it]

Kích thước finetune_set hiện tại: 1321
Loading finetuning data...

========== STEP 36/201 ==========

100%|██████████| 1/1 [03:09<00:00, 189.25s/it]

Kích thước finetune_set hiện tại: 1335
Loading finetuning data...

========== STEP 37/201 ==========

100%|██████████| 1/1 [03:09<00:00, 189.44s/it]

Kích thước finetune_set hiện tại: 1348
Loading finetuning data...

========== STEP 38/201 ==========

100%|██████████| 1/1 [03:09<00:00, 189.04s/it]

Kích thước finetune_set hiện tại: 1353
Loading finetuning data...

========== STEP 39/201 ==========

100%|██████████| 1/1 [03:10<00:00, 190.42s/it]

Kích thước finetune_set hiện tại: 1364
Loading finetuning data...

========== STEP 40/201 ==========

100%|██████████| 1/1 [03:09<00:00, 189.43s/it]

Kích thước finetune_set hiện tại: 1379
Loading finetuning data...

========== STEP 41/201 ==========

100%|██████████| 1/1 [03:10<00:00, 190.80s/it]

Kích thước finetune_set hiện tại: 1399
Loading finetuning data...

Đã lưu/cập nhật 1399 mẫu vào /kaggle/working/silver_data.json
Đã cập nhật new_train_set vào /kaggle/working/new_train_set.json

100%|██████████| 2/2 [03:09<00:00, 94.91s/it]

Validation accuracy: 0.75

========== STEP 42/201 ==========

100%|██████████| 1/1 [03:09<00:00, 189.02s/it]

Kích thước finetune_set hiện tại: 1412
Loading finetuning data...

========== STEP 43/201 ==========

100%|██████████| 1/1 [03:09<00:00, 189.36s/it]

Kích thước finetune_set hiện tại: 1422
Loading finetuning data...

========== STEP 44/201 ==========

100%|██████████| 1/1 [03:10<00:00, 190.03s/it]

Kích thước finetune_set hiện tại: 1436
Loading finetuning data...

========== STEP 45/201 ==========

100%|██████████| 1/1 [03:12<00:00, 192.16s/it]

Kích thước finetune_set hiện tại: 1451
Loading finetuning data...

========== STEP 46/201 ==========

100%|██████████| 1/1 [03:10<00:00, 190.80s/it]

Kích thước finetune_set hiện tại: 1457
Loading finetuning data...

========== STEP 47/201 ==========

100%|██████████| 1/1 [03:10<00:00, 191.00s/it]

Kích thước finetune_set hiện tại: 1473
Loading finetuning data...

========== STEP 48/201 ==========

100%|██████████| 1/1 [03:12<00:00, 192.08s/it]

Kích thước finetune_set hiện tại: 1485
Loading finetuning data...

========== STEP 49/201 ==========

100%|██████████| 1/1 [03:10<00:00, 190.42s/it]

Kích thước finetune_set hiện tại: 1497
Loading finetuning data...

========== STEP 50/201 ==========

100%|██████████| 1/1 [03:12<00:00, 192.36s/it]

Kích thước finetune_set hiện tại: 1516
Loading finetuning data...

========== STEP 51/201 ==========

100%|██████████| 1/1 [03:12<00:00, 192.77s/it]

Kích thước finetune_set hiện tại: 1539
Loading finetuning data...

Đã lưu/cập nhật 1539 mẫu vào /kaggle/working/silver_data.json
Đã cập nhật new_train_set vào /kaggle/working/new_train_set.json

100%|██████████| 2/2 [03:58<00:00, 119.25s/it]

Validation accuracy: 0.725

========== STEP 52/201 ==========

100%|██████████| 1/1 [03:13<00:00, 193.58s/it]

Kích thước finetune_set hiện tại: 1557
Loading finetuning data...

========== STEP 53/201 ==========

  0%|          | 0/1 [01:08<?, ?it/s]

KeyboardInterrupt: